//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintTb
    {
        public int Id { get; set; }
        public Nullable<int> houseid { get; set; }
        public string complaint { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Title { get; set; }
        public int employeeid { get; set; }
    }
}
