//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorTb
    {
        public ContractorTb()
        {
            this.ProjectAssignedTbs = new HashSet<ProjectAssignedTb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Company { get; set; }
        public string CNIC { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string NTN { get; set; }
    
        public virtual ICollection<ProjectAssignedTb> ProjectAssignedTbs { get; set; }
    }
}
