//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FalconHouseEntities1 : DbContext
    {
        public FalconHouseEntities1()
            : base("name=FalconHouseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Access> Accesses { get; set; }
        public DbSet<Advance> Advances { get; set; }
        public DbSet<AdvanceReturn> AdvanceReturns { get; set; }
        public DbSet<Alert> Alerts { get; set; }
        public DbSet<Allottee> Allottees { get; set; }
        public DbSet<AltrationTb> AltrationTbs { get; set; }
        public DbSet<CareOf> CareOfs { get; set; }
        public DbSet<CategoryTb> CategoryTbs { get; set; }
        public DbSet<ComercialAllottment> ComercialAllottments { get; set; }
        public DbSet<ComplaintTb> ComplaintTbs { get; set; }
        public DbSet<Contractor> Contractors { get; set; }
        public DbSet<ContractorTb> ContractorTbs { get; set; }
        public DbSet<dbFile> dbFiles { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeSalary> EmployeeSalaries { get; set; }
        public DbSet<EmployeesAttendance> EmployeesAttendances { get; set; }
        public DbSet<Expens> Expenses { get; set; }
        public DbSet<FamilytreeTB> FamilytreeTBs { get; set; }
        public DbSet<Fine> Fines { get; set; }
        public DbSet<House> Houses { get; set; }
        public DbSet<HouseBill> HouseBills { get; set; }
        public DbSet<ImagesPath> ImagesPaths { get; set; }
        public DbSet<InvTransferTb> InvTransferTbs { get; set; }
        public DbSet<IssueDetailTb> IssueDetailTbs { get; set; }
        public DbSet<ItemsDeff> ItemsDeffs { get; set; }
        public DbSet<MarketTb> MarketTbs { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PaymentDetail> PaymentDetails { get; set; }
        public DbSet<Pet> Pets { get; set; }
        public DbSet<ProgressTb> ProgressTbs { get; set; }
        public DbSet<ProjectAssignedTb> ProjectAssignedTbs { get; set; }
        public DbSet<ProjectMeterialIssuTb> ProjectMeterialIssuTbs { get; set; }
        public DbSet<ProjectTb> ProjectTbs { get; set; }
        public DbSet<ProjectTbNew> ProjectTbNews { get; set; }
        public DbSet<ProjectTypeTb> ProjectTypeTbs { get; set; }
        public DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public DbSet<Purchaser> Purchasers { get; set; }
        public DbSet<PurchaseTb> PurchaseTbs { get; set; }
        public DbSet<RAC> RACs { get; set; }
        public DbSet<RarReceiptTb> RarReceiptTbs { get; set; }
        public DbSet<RarTb> RarTbs { get; set; }
        public DbSet<RenteePaymentTb> RenteePaymentTbs { get; set; }
        public DbSet<Resident> Residents { get; set; }
        public DbSet<ResidentsInfo> ResidentsInfoes { get; set; }
        public DbSet<ResidentTb> ResidentTbs { get; set; }
        public DbSet<Servant> Servants { get; set; }
        public DbSet<ShopCurrentTb> ShopCurrentTbs { get; set; }
        public DbSet<ShopsRent> ShopsRents { get; set; }
        public DbSet<ShopsTb> ShopsTbs { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Tenant> Tenants { get; set; }
        public DbSet<UOMTb> UOMTbs { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<vaccinTb> vaccinTbs { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
        public DbSet<VehicleTb> VehicleTbs { get; set; }
        public DbSet<VisiterTb> VisiterTbs { get; set; }
        public DbSet<Visitor> Visitors { get; set; }
        public DbSet<YardStick> YardSticks { get; set; }
        public DbSet<ColorTb> ColorTbs { get; set; }
    }
}
