//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesAttendance
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TimeDue { get; set; }
        public string Arrival { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
