//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Advances = new HashSet<Advance>();
            this.AdvanceReturns = new HashSet<AdvanceReturn>();
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
            this.EmployeesAttendances = new HashSet<EmployeesAttendance>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string ContactNo { get; set; }
        public string Designation { get; set; }
        public string CNIC { get; set; }
        public string BloodGroup { get; set; }
        public string Srnumber { get; set; }
        public Nullable<System.DateTime> Cardexp { get; set; }
        public Nullable<System.DateTime> CardIssue { get; set; }
        public string Occupation { get; set; }
        public string CardStatus { get; set; }
        public string CardTrackNote { get; set; }
        public string Img { get; set; }
        public string Sof { get; set; }
        public string Address { get; set; }
        public Nullable<int> Selected { get; set; }
    
        public virtual ICollection<Advance> Advances { get; set; }
        public virtual ICollection<AdvanceReturn> AdvanceReturns { get; set; }
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual ICollection<EmployeesAttendance> EmployeesAttendances { get; set; }
    }
}
