//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public Expens()
        {
            this.HouseBills = new HashSet<HouseBill>();
        }
    
        public int Id { get; set; }
        public string Head { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<HouseBill> HouseBills { get; set; }
    }
}
