//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilytreeTB
    {
        public int Id { get; set; }
        public string type { get; set; }
        public int sponsirid { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string Relation { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Img { get; set; }
        public Nullable<int> Selected { get; set; }
        public string CardTrackNote { get; set; }
        public string CardStatus { get; set; }
        public Nullable<System.DateTime> CardIssue { get; set; }
        public Nullable<System.DateTime> Cardexp { get; set; }
        public string Srnumber { get; set; }
        public string so { get; set; }
        public string soname { get; set; }
    }
}
