//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseBill
    {
        public int Id { get; set; }
        public Nullable<int> HouseId { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ExpenseId { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Status { get; set; }
        public string BillingMonth { get; set; }
        public Nullable<double> Payable { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Arears { get; set; }
        public Nullable<double> Surcharge { get; set; }
    
        public virtual Expens Expens { get; set; }
        public virtual House House { get; set; }
    }
}
