//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Allottees = new HashSet<Allottee>();
            this.HouseBills = new HashSet<HouseBill>();
            this.Payments = new HashSet<Payment>();
            this.Purchasers = new HashSet<Purchaser>();
            this.Residents = new HashSet<Resident>();
            this.ResidentTbs = new HashSet<ResidentTb>();
            this.Tenants = new HashSet<Tenant>();
        }
    
        public int Id { get; set; }
        public string HouseNo { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Allottee> Allottees { get; set; }
        public virtual ICollection<HouseBill> HouseBills { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Purchaser> Purchasers { get; set; }
        public virtual ICollection<Resident> Residents { get; set; }
        public virtual ICollection<ResidentTb> ResidentTbs { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
    }
}
