//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetailTb
    {
        public int Id { get; set; }
        public Nullable<int> Issueid { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> Total { get; set; }
        public string Detail { get; set; }
    
        public virtual ProjectMeterialIssuTb ProjectMeterialIssuTb { get; set; }
    }
}
