//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsDeff
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Catid { get; set; }
        public string ItemCode { get; set; }
    
        public virtual CategoryTb CategoryTb { get; set; }
    }
}
