//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketTb
    {
        public MarketTb()
        {
            this.ComercialAllottments = new HashSet<ComercialAllottment>();
            this.ShopsTbs = new HashSet<ShopsTb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public string Allottee { get; set; }
        public string CNIC { get; set; }
        public string SO { get; set; }
        public string SoName { get; set; }
        public string Gender { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<ComercialAllottment> ComercialAllottments { get; set; }
        public virtual ICollection<ShopsTb> ShopsTbs { get; set; }
    }
}
