//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int Id { get; set; }
        public Nullable<int> PayId { get; set; }
        public Nullable<double> Paid { get; set; }
        public string BillingMonth { get; set; }
        public Nullable<double> Remaining { get; set; }
        public string type { get; set; }
        public Nullable<double> Arear { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
