//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int Id { get; set; }
        public Nullable<int> ResId { get; set; }
        public string Pet_Kind { get; set; }
        public Nullable<System.DateTime> Vaccinated { get; set; }
        public Nullable<System.DateTime> Vaccinated_Due { get; set; }
        public string ownby { get; set; }
        public Nullable<int> memberid { get; set; }
    }
}
