//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressTb
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> passinid { get; set; }
        public Nullable<int> stickid { get; set; }
        public Nullable<double> GF { get; set; }
        public Nullable<double> FF { get; set; }
    
        public virtual ProjectAssignedTb ProjectAssignedTb { get; set; }
        public virtual YardStick YardStick { get; set; }
    }
}
