//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTbNew
    {
        public ProjectTbNew()
        {
            this.ProjectAssignedTbs = new HashSet<ProjectAssignedTb>();
        }
    
        public int Id { get; set; }
        public string Pname { get; set; }
        public string PHnumber { get; set; }
        public string Phtype { get; set; }
        public Nullable<int> ptypeid { get; set; }
    
        public virtual ICollection<ProjectAssignedTb> ProjectAssignedTbs { get; set; }
        public virtual ProjectTypeTb ProjectTypeTb { get; set; }
    }
}
