//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMeterialIssuTb
    {
        public ProjectMeterialIssuTb()
        {
            this.IssueDetailTbs = new HashSet<IssueDetailTb>();
        }
    
        public int Id { get; set; }
        public Nullable<int> passignid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> Amount { get; set; }
        public string status { get; set; }
        public Nullable<int> rarid { get; set; }
    
        public virtual ICollection<IssueDetailTb> IssueDetailTbs { get; set; }
    }
}
