//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTb
    {
        public int Id { get; set; }
        public Nullable<int> contractor { get; set; }
        public string Name { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<double> EstimatedCost { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> AssigningDate { get; set; }
        public string PDetail { get; set; }
    }
}
