//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTb
    {
        public PurchaseTb()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Supplierid { get; set; }
        public Nullable<int> Numberitems { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Terminal { get; set; }
        public string InoviceNumber { get; set; }
        public string purchasefor { get; set; }
    
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
