//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int Id { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<double> Packages { get; set; }
        public Nullable<double> ItemspPackage { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> PricepPckage { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> pricepItem { get; set; }
        public Nullable<int> puid { get; set; }
    
        public virtual PurchaseTb PurchaseTb { get; set; }
    }
}
