//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RarTb
    {
        public RarTb()
        {
            this.RarReceiptTbs = new HashSet<RarReceiptTb>();
        }
    
        public int Id { get; set; }
        public string rarnumber { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> onprogress { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> pasind { get; set; }
        public string RarDocument { get; set; }
        public Nullable<bool> SDOapp { get; set; }
        public Nullable<bool> Adapp { get; set; }
        public Nullable<bool> SDOeng { get; set; }
        public Nullable<bool> WOic { get; set; }
        public Nullable<bool> DDH { get; set; }
        public Nullable<bool> Director { get; set; }
        public Nullable<bool> ICCash { get; set; }
    
        public virtual ProjectAssignedTb ProjectAssignedTb { get; set; }
        public virtual ICollection<RarReceiptTb> RarReceiptTbs { get; set; }
    }
}
