//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenteePaymentTb
    {
        public int id { get; set; }
        public string voucher { get; set; }
        public Nullable<int> renteeid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<int> shopid { get; set; }
    
        public virtual ShopCurrentTb ShopCurrentTb { get; set; }
        public virtual ShopsTb ShopsTb { get; set; }
    }
}
