//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public Resident()
        {
            this.Documents = new HashSet<Document>();
            this.ResidentsInfoes = new HashSet<ResidentsInfo>();
            this.Servants1 = new HashSet<Servant>();
            this.Vehicles1 = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HouseId { get; set; }
        public string Floors { get; set; }
        public Nullable<int> Pets { get; set; }
        public Nullable<int> vehicles { get; set; }
        public Nullable<int> ResidentsNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> servants { get; set; }
        public string profession { get; set; }
        public string CNIC { get; set; }
        public string Nationality { get; set; }
        public string BloodGroup { get; set; }
        public string ContactPerson { get; set; }
        public string Gender { get; set; }
        public Nullable<int> tenantid { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual House House { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<ResidentsInfo> ResidentsInfoes { get; set; }
        public virtual ICollection<Servant> Servants1 { get; set; }
        public virtual ICollection<Vehicle> Vehicles1 { get; set; }
    }
}
