//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentsInfo
    {
        public int Id { get; set; }
        public Nullable<int> ResId { get; set; }
        public string Name { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string Blood_Group { get; set; }
        public string CNIC_NO { get; set; }
        public string Nationality { get; set; }
        public string Relation_To_The_ContactPerson { get; set; }
    
        public virtual Resident Resident { get; set; }
    }
}
