//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCurrentTb
    {
        public ShopCurrentTb()
        {
            this.RenteePaymentTbs = new HashSet<RenteePaymentTb>();
        }
    
        public int Id { get; set; }
        public Nullable<int> shopid { get; set; }
        public string Name { get; set; }
        public string SO { get; set; }
        public string SofName { get; set; }
        public string CNIC { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string srnumber { get; set; }
        public Nullable<System.DateTime> cardexp { get; set; }
        public Nullable<System.DateTime> cardissu { get; set; }
        public string CardStatus { get; set; }
        public string CardTrackNote { get; set; }
        public Nullable<int> Selected { get; set; }
        public string TypeStat { get; set; }
        public Nullable<double> SecuerityDeposit { get; set; }
        public Nullable<System.DateTime> AgrementEnd { get; set; }
        public string Status { get; set; }
        public string Businessname { get; set; }
    
        public virtual ICollection<RenteePaymentTb> RenteePaymentTbs { get; set; }
        public virtual ShopsTb ShopsTb { get; set; }
    }
}
