//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopsTb
    {
        public ShopsTb()
        {
            this.RenteePaymentTbs = new HashSet<RenteePaymentTb>();
            this.ShopCurrentTbs = new HashSet<ShopCurrentTb>();
            this.ShopsRents = new HashSet<ShopsRent>();
        }
    
        public int Id { get; set; }
        public string ShopeNumber { get; set; }
        public Nullable<int> marketid { get; set; }
        public string Detail { get; set; }
    
        public virtual MarketTb MarketTb { get; set; }
        public virtual ICollection<RenteePaymentTb> RenteePaymentTbs { get; set; }
        public virtual ICollection<ShopCurrentTb> ShopCurrentTbs { get; set; }
        public virtual ICollection<ShopsRent> ShopsRents { get; set; }
    }
}
