//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccinTb
    {
        public int id { get; set; }
        public Nullable<int> petid { get; set; }
        public string vaccin { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> nextdate { get; set; }
    }
}
