//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public Nullable<int> ResId { get; set; }
        public string RegNo { get; set; }
        public string Make { get; set; }
        public Nullable<float> ModelNo { get; set; }
        public string Color { get; set; }
        public string EtagId { get; set; }
    
        public virtual Resident Resident { get; set; }
    }
}
