//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisiterTb
    {
        public int Id { get; set; }
        public string Vhnumber { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string CNIC { get; set; }
        public string VisitTo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Ingate { get; set; }
        public string Outgate { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
    }
}
