//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int Id { get; set; }
        public string VehicalNo { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string CNIC { get; set; }
        public string VisitTo { get; set; }
        public string InGate { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public string OutGate { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string Remarks { get; set; }
        public string PIcture1 { get; set; }
        public string Picture2 { get; set; }
    }
}
