//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalconReportingweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class YardStick
    {
        public YardStick()
        {
            this.ProgressTbs = new HashSet<ProgressTb>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> GF { get; set; }
        public Nullable<double> FF { get; set; }
    
        public virtual ICollection<ProgressTb> ProgressTbs { get; set; }
    }
}
